### ISSUE TITLE
Failed to resolve: com.google.android.mobly:snippetlib:0.0.1

### ISSUE THREAD

**Issue by sravanmedarapu** [google/mobly-snippet-lib#11]
Trying to create a standalone Mobly snippet app as mention [here](https://github.com/google/mobly-snippet-lib/tree/master/examples/1_standalone_app#tutorial), but unable to resolve dependency `com.google.android.mobly:snippetlib`

```
dependencies {
      compile 'com.google.android.mobly:snippetlib:0.0.1'
 }
```

**Comment by adorokhine** [comment]
Thanks for reporting! We are working on getting this uploaded to the maven
repo but the winter holidays have slowed us down a bit. In the meantime you
can clone this project and start developing a snippet alongside the
examples tree, or drop the code into your project so you can use a project
dep in your Gradle file.

Sorry about that! We'll have it uploaded soon.

**Comment by sravanmedarapu** [comment]
Sure, Thanks for the info :)

**Comment by adorokhine** [comment]
This artifact is now uploaded to jcenter, so it should work if you compile like this:
compile 'com.google.android.mobly:mobly-snippet-lib:1.0.0'

Please test it out and let us know!
