### ISSUE TITLE
More entries in .gitignore

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly-snippet-lib#12]
to exclude cache files generated during build time

**Comment by dthkao** [comment]
Is this still an issue?

**Comment by xpconanfan** [comment]
I think so, unless there was a fix checked in without closing this

**Comment by dthkao** [comment]
Is this a Mac specific issue? I see nothing in git status after building on linux.

**Comment by xpconanfan** [comment]
Hmm, it might be. I'm not sure

**Comment by xpconanfan** [comment]
Fixed
