### ISSUE TITLE
Add a way to retrieve the list of permissions to grant a snippet apk

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly-snippet-lib#24]
Due to the permission changes in M, we need a way to grant snippet permissions.
So let's have a 'secret' Rpc call to retrieve the list of permissions required.

**Comment by adorokhine** [comment]
Does installing with -g help here?

**Comment by xpconanfan** [comment]
It might be the solution. Will need to try on a non-rootable device first.

**Comment by xpconanfan** [comment]
`-g` worked
