### ISSUE TITLE
Add an way to tag Rpc methods for categorization purposes

### ISSUE THREAD

**Issue by xpconanfan** [google/mobly-snippet-lib#44]
Right now `help()` prints out all methods altogether, as the number of methods increase, we need to be able to categorize Rpc methods. Instead of a long consecutive list in alphabetic order, we probably want `help()`'s output to be more organized and readable:

```
Bluetooth:
  bluetoothDisable() returns void  // Disable bluetooth with a 30s timeout.
  bluetoothEnable() returns void  // Enable bluetooth with a 30s timeout.

Telephony:
  getLine1Number() returns String  // Gets the line 1 phone number.
  getSubscriberId() returns String  // Returns the unique subscriber ID, for example, the IMSI for a GSM phone.
  getTelephonyCallState() returns int  // Gets the call state for the default subscription. Call state values are0: IDLE, 1: RINGING, 2: OFFHOOK

Audio:
  getMusicMaxVolume() returns int  // Gets the maximum music stream volume value.
  getMusicVolume() returns int  // Gets the music stream volume.
  getRingMaxVolume() returns int  // Gets the maximum ringer volume value.
  getRingVolume() returns int  // Gets the ringer volume.

Account:
  listAccounts() returns Set  // List all Google (GMail) accounts on the device.

Others:
  makeToast(String) returns void  // Make a toast on screen.
  muteAll() returns void  // Silences all audio streams.
```

We could add a new field in `@Rpc` to specify the categorization of each method.

**Comment by adorokhine** [comment]
Let's just print by class. No need to add extra complexity.

**Comment by xpconanfan** [comment]
That may not work as we have more classes, for example, wifi may have multiple classes.

**Comment by adorokhine** [comment]
When it stops working, let's reconsider. I really don't want to start adding complexity where we don't need it. For now I think categorizing by class will be fine and is simple and doesn't require user involvement.

**Comment by dthkao** [comment]
For wifi, even if we have multiple classes, couldn't we have one main class
for the wifi Rpcs and then helper/utils?

                    davidkao

**Comment by xpconanfan** [comment]
If you print MBS's `help()` today, the list is already dubiously long and the Rpcs are not grouped by class, they are listed in alphabetic order and hard to read.

We could fix that first and consider adding extra field later.

**Comment by adorokhine** [comment]
Agreed, let's do grouping by class for now.
